<?php

$modversion['name'] = _ME_MULTIED_NAME;
$modversion['version'] = 0.03;
$modversion['description'] = _ME_MULTIED_DESC;
$modversion['credits'] = _ME_MULTIED_CRED;
$modversion['author'] = _ME_MULTIED_AUTH;
$modversion['license'] = _ME_MULTIED_LICENCE;
$modversion['official'] = 0;
$modversion['image'] = "images/multieditor.png" ;
$modversion['help'] = "";
$modversion['dirname'] = "multieditor";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'multieditor_editors';
$modversion['tables'][1] = 'multieditor_groups_modules_array';

// Admin
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['hasComments'] = 0;
$modversion['hasNotification'] = 0;

// Config categories

//Config options
?>
